AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  restaurant-line-bot

  Sample SAM Template for restaurant-line-bot

Parameters:
  LineSecretToken:
    Type: String
    Description: LINE Secret Token
  LineAccessToken:
    Type: String
    Description: LINE Access Token
  HotpepperApiKey:
    Type: String
    Description: Hotpepper API Key

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  RestaurantLineBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/restaurant-line-bot/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /restaurant/api/{proxy+}
            Method: POST
      Environment:
        Variables:
          LINE_SECRET_TOKEN: !Ref LineSecretToken
          LINE_ACCESS_TOKEN: !Ref LineAccessToken
          HOTPEPPER_API_KEY: !Ref HotpepperApiKey

Outputs:
  RestaurantLineBotApi:
    Description: 'API Gateway endpoint URL for Prod stage for RestaurantLineBot function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/restaurant/'
  RestaurantLineBotFunction:
    Description: 'RestaurantLineBot Lambda Function ARN'
    Value: !GetAtt RestaurantLineBotFunction.Arn
  RestaurantLineBotFunctionIamRole:
    Description: 'Implicit IAM Role created for RestaurantLineBot function'
    Value: !GetAtt RestaurantLineBotFunctionRole.Arn
